# Generated by Django 5.0.3 on 2024-03-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SchoolName', models.CharField(max_length=255)),
                ('Year', models.IntegerField()),
                ('StudentID', models.IntegerField()),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('YearLevel', models.CharField(max_length=255)),
                ('Class', models.CharField(max_length=255)),
                ('Subject', models.CharField(max_length=255)),
                ('Answers', models.CharField(max_length=255)),
                ('CorrectAnswers', models.CharField(max_length=255)),
                ('QuestionNumber', models.IntegerField()),
                ('SubjectContents', models.CharField(max_length=255)),
                ('AssessmentAreas', models.CharField(max_length=255)),
                ('SydneyCorrectCountPercentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('SydneyAverageScore', models.DecimalField(decimal_places=2, max_digits=5)),
                ('SydneyParticipants', models.IntegerField()),
                ('StudentScore', models.DecimalField(decimal_places=2, max_digits=5)),
                ('StudentTotalAssessed', models.IntegerField()),
                ('StudentAreaAssessedScore', models.DecimalField(decimal_places=2, max_digits=5)),
                ('TotalAreaAssessedScore', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Participant', models.CharField(max_length=255)),
                ('CorrectAnswerPercentagePerClass', models.DecimalField(decimal_places=2, max_digits=5)),
                ('AverageScore', models.DecimalField(decimal_places=2, max_digits=5)),
                ('SchoolPercentile', models.DecimalField(decimal_places=2, max_digits=5)),
                ('SydneyPercentile', models.DecimalField(decimal_places=2, max_digits=5)),
                ('StrengthStatus', models.CharField(max_length=255)),
                ('HighDistinctCount', models.IntegerField()),
                ('DistinctCount', models.IntegerField()),
                ('CreditCount', models.IntegerField()),
                ('ParticipantCount', models.IntegerField()),
                ('Award', models.CharField(max_length=255)),
            ],
        ),
    ]
