# Generated by Django 5.0.3 on 2024-03-11 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.class')),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.school')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubjectName', models.CharField(max_length=255)),
                ('StudentScore', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SydneyParticipant', models.CharField(max_length=255)),
                ('SydneyPercentile', models.DecimalField(decimal_places=2, max_digits=5)),
                ('CorrectAnswerPercentagePerClass', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Participant', models.CharField(max_length=255)),
                ('StudentScore', models.DecimalField(decimal_places=2, max_digits=5)),
                ('YearLevelName', models.CharField(max_length=255)),
                ('Answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.answers')),
                ('AssessmentArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.assessmentareas')),
                ('Award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.awards')),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.class')),
                ('CorrectAnswer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answers', to='main.answers')),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.school')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='AssessmentData',
        ),
    ]
